### ISSUE TITLE
Error when emerging media-sound/deepin-music: /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -ldmusic collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by SleepyMario** [zhtengw/deepin-overlay#51] opened 2018-12-02 11:32 UTC
Hello. I ran this error when emerging media-sound/deepin-music-3.1.11 : 
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -ldmusic
collect2: error: ld returned 1 exit status

I have no idea how to fix this. The links below have some logs and build info:

 

- build log: 
https://paste.pound-python.org/show/LMc2C8wScGnKfxletTkl/

- emerge --info =media-sound/deepin-music-3.1.11::deepin 
https://paste.pound-python.org/show/IwkViiryUe9ZWe0SXSJw/

- emerge -pqv =media-sound/deepin-music-3.1.11::deepin 
https://paste.pound-python.org/show/VtsqFLcZ5wnIAje1oED8/

**Comment by zhtengw** [comment] 2018-12-07 14:07
I cannot reproduce this issue. And so far I have no idea to fix it.

**Comment by SleepyMario** [comment] 2018-12-07 15:32
that's a pity

**Comment by zhtengw** [comment] 2018-12-11 08:48
I have tested with gcc-7.3.0 and binutils-2.30.0, cannot reproduce either.
Maybe, you can remerge your sys-devel/binutils to have a try.

**Comment by barolo** [comment] 2019-02-06 13:30
Unsure if it's related but deepin-movie-reborn fails linking phase too, with gold linker, switching to ld.bfd fixes it

**Comment by zhtengw** [comment] 2019-04-26 12:43
Fixed with https://github.com/zhtengw/deepin-overlay/commit/b973e590ea6c642fadad9c403111839e24a56a6b

**Closed by zhtengw** 2019-04-26 12:43 UTC
