### ISSUE TITLE
Openrc with deepin

### ISSUE THREAD

**Issue by Fulgurance** [zhtengw/deepin-overlay#47] opened 2018-09-21 08:32 UTC
Hello, I have juste one question, is it possible deepin work with openrc ?

And is it possible to use dde-session-ui without systemd ?

**Comment by zhtengw** [comment] 2018-09-22 00:09
Sorry, I haven't tried and I don't know if deepin desktop environment can run with openrc or not. And the dde-session-ui is designed to run on systemd, so it is not possible to use dde-session-ui without systemd.

**Comment by SleepyMario** [comment] 2018-11-15 10:21
i did try it a little while ago. it will boot up, but the menuing will be off. sadly i'm not knowledgeable enough to do something about it.

**Comment by tefiszx** [comment] 2019-04-20 02:41
我的gentoo用的也是openrc。也比较难以接受systemd

**Comment by zhtengw** [comment] 2019-04-24 14:44
[dde-daemon](https://github.com/linuxdeepin/dde-daemon), which is the base runtime daemon of DDE, can not run without systemd.

**Comment by zhtengw** [comment] 2019-04-25 04:57
I am the only maintainer of deepin-overlay, and I don't have enough time and energy to patch DDE
to run without systemd. I will be appreciative if someone can help me.

**Comment by zhtengw** [comment] 2019-04-27 04:09
@Fulgurance @SleepyMario @tefiszx Hi all, I spend some time this weekend to do a clean installation of gentoo and DDE. And I try to build up DDE without systemd. Could you please refer the guide in README.md and have a try? If you get any issues, please let me know.

**Comment by SleepyMario** [comment] 2019-04-27 05:05
Sure. One of these days I'll do an install and report back here.

**Comment by SleepyMario** [comment] 2019-04-29 07:05
I quickly tried something in a VM and ran into issues when comping dde-terminal and (especially) dde-files. The dde-files one was Kencoding related, deepin-terminal probably needs gnome-base/librsvg with the vala flag turned on? I still ran into some issues afterward changing that.
You probably need some logs; I will do a new attempt soon and gather the logs.

**Comment by zhtengw** [comment] 2019-04-29 08:54
@SleepyMario Thank you. I tested deepin-terminal with librsvg and confirmed this. Fixed with https://github.com/zhtengw/deepin-overlay/commit/a6fd3ac090649a66f4664c36adb72d346de63216.

**Comment by SleepyMario** [comment] 2019-05-02 16:13
I'm doing an installation on real hardware atm and have problems emerging deepin-terminal and deepin-wm. Here are the logs: http://dpaste.com/3CJ7Y6S and http://dpaste.com/0KJ1P37

emerge --info --> http://dpaste.com/1N7SD7X

Let me know if you need other information.

**Comment by zhtengw** [comment] 2019-05-03 02:38
1. deepin-terminal need x11-libs/vte to be higher than 0.50.1, I forgot to add the version dependency when I disabled deepin-terminal to build with vendor(https://github.com/zhtengw/deepin-overlay/commit/1e900363a08e02e09288d49f87e9b8caeed366c4). I will fix it.

2. deepin-wm need x11-wm/deepin-mutter, and I surely wrote it to the dependencies list. I cannot find out why it declared not find libdeepin-mutter in the system.

**Comment by SleepyMario** [comment] 2019-05-03 06:51
1) on x11-wm/deepin-mutter: I think I found the problem. It will complain about not being able to find systemd and then instead of compiling just install a few docs only.

2) The geoip database locations for dde-base/dde-control-center probably need to be updated? I'm getting "Error 404: Not Found." for every single one of them.

3) I got around this for now by just switching to systemd and am getting an error with dde-base/dde-file-manager (this one has been popping up on the VM as well). For some reason my usual pastebin is not working, so I'll post (what I think is) the relevant information below:

--------
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-desktop/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::~KEncodingProber()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-desktop/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::setProberType(KEncodingProber::ProberType)'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-desktop/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::confidence() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-desktop/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::encoding() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-desktop/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::KEncodingProber(KEncodingProber::ProberType)'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-desktop/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::feed(QByteArray const&)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:298: dde-desktop] Error 1
make[1]: Leaving directory '/var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-desktop'
make: *** [Makefile:180: sub-dde-desktop-make_first] Error 2
x86_64-pc-linux-gnu-g++ -Wl,-O1 -Wl,--as-needed -o dde-file-manager-daemon command.o partitionmanager.o partition.o string_util.o structs.o readusagemanager.o main.o filemanagerdaemon.o appcontroller.o fileoperation.o renamejob.o fileoperation_adaptor.o renamejob_adaptor.o fileoperation_interface.o renamejob_interface.o filemanagerclient.o dbusinforet.o policykithelper.o basejob.o createfolderjob.o createtemplatefilejob.o movejob.o copyjob.o deletejob.o copyjob_adaptor.o createfolderjob_adaptor.o createtemplatefilejob_adaptor.o deletejob_adaptor.o movejob_adaptor.o copyjob_interface.o createfolderjob_interface.o createtemplatefilejob_interface.o deletejob_interface.o movejob_interface.o usersharemanager.o usershare_adaptor.o usershare_interface.o usbformatter.o usbformatter_adaptor.o usbformatter_interface.o commandmanager.o commandmanager_adaptor.o commandmanager_interface.o deviceinfomanager.o deviceinfomanager_adaptor.o deviceinfomanager_interface.o tagmanagerdaemon.o tagmanagerdaemon_adaptor.o moc_partitionmanager.o moc_readusagemanager.o moc_filemanagerdaemon.o moc_appcontroller.o moc_fileoperation.o moc_renamejob.o moc_fileoperation_adaptor.o moc_renamejob_adaptor.o moc_fileoperation_interface.o moc_renamejob_interface.o moc_filemanagerclient.o moc_basejob.o moc_createfolderjob.o moc_createtemplatefilejob.o moc_movejob.o moc_copyjob.o moc_deletejob.o moc_copyjob_adaptor.o moc_createfolderjob_adaptor.o moc_createtemplatefilejob_adaptor.o moc_deletejob_adaptor.o moc_movejob_adaptor.o moc_copyjob_interface.o moc_createfolderjob_interface.o moc_createtemplatefilejob_interface.o moc_deletejob_interface.o moc_movejob_interface.o moc_usersharemanager.o moc_usershare_adaptor.o moc_usershare_interface.o moc_usbformatter.o moc_usbformatter_adaptor.o moc_usbformatter_interface.o moc_commandmanager.o moc_commandmanager_adaptor.o moc_commandmanager_interface.o moc_deviceinfomanager.o moc_deviceinfomanager_adaptor.o moc_deviceinfomanager_interface.o moc_tagmanagerdaemon.o moc_tagmanagerdaemon_adaptor.o   -L/var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-file-manager-daemon/../dde-file-manager-lib -ldde-file-manager -lX11 -lpolkit-agent-1 -lpolkit-gobject-1 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpolkit-qt5-gui-1 -lpolkit-qt5-core-1 -lpolkit-qt5-agent-1 -lQt5Gui -ldtkwidget -ldtkcore -lQt5DBus -lQt5Concurrent -lQt5Core -lpthread   
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-file-manager-daemon/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::~KEncodingProber()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-file-manager-daemon/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::setProberType(KEncodingProber::ProberType)'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-file-manager-daemon/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::confidence() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-file-manager-daemon/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::encoding() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-file-manager-daemon/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::KEncodingProber(KEncodingProber::ProberType)'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-file-manager-daemon/../dde-file-manager-lib/libdde-file-manager.so: undefined reference to `KEncodingProber::feed(QByteArray const&)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:341: dde-file-manager-daemon] Error 1
make[1]: Leaving directory '/var/tmp/portage/dde-base/dde-file-manager-4.8.3/work/dde-file-manager-4.8.3/dde-file-manager-daemon'
make: *** [Makefile:80: sub-dde-file-manager-daemon-make_first] Error 2
 * ERROR: dde-base/dde-file-manager-4.8.3::deepin failed (compile phase):
 *   emake failed
---------------

**Comment by SleepyMario** [comment] 2019-05-03 07:29
I tried to emerge dde-base/dde-meta with the kwin flag turned on as well (systemd), and run into this error when compiling x11-wm/dde-kwin --> http://dpaste.com/0DXNZKX

**Comment by zhtengw** [comment] 2019-05-03 15:58
Hi @SleepyMario, I think you built some Kde-framwork libs with previous version of gcc. You may fix these "undefined reference" by rebuilding them. Rebuild kde-frameworks/kcodecs for your dde-file-manager issue, and rebuild kde-frameworks/kwindowsystem, kde-frameworks/kglobalaccel, kde-frameworks/kconfig for dde-kwin issue.

**Comment by SleepyMario** [comment] 2019-05-03 19:02
Hello @zhtengw, everything is working now (with systemd). It turned out to be an issue with the kde-frameworks packages you mentioned; The unstable versions (5.57.0) should be used instead of the stable ones (5.54.0-r1). I've just rebuild all the kde-frameworks/* with the unstable versions and then everything works fine (with gcc-8.2.0-r6, current stable). I'll try to convert the installation to openrc soon and will post some logs.

**Comment by zhtengw** [comment] 2019-05-04 01:59
OK, as mentioned in my installation guide, accepted testing keywords system-wide should be done to avoid issues.

Best regards
Aten

**Comment by SleepyMario** [comment] 2019-05-04 05:56
No wonder I ran into so many minor issues, I completely missed that for some reason. I will test openrc today then.

**Comment by zhtengw** [comment] 2019-05-04 10:35
@SleepyMario. Sorry if my words make you unhappy. I just tested dde-file-manager with kcodecs-5.54 and everything work. So you may just rebuild these KF libs with current installed gcc to fix issues, as I said in https://github.com/zhtengw/deepin-overlay/issues/47#issuecomment-489147779

**Comment by SleepyMario** [comment] 2019-05-04 12:31
@zhtengw No problem, thanks for the advice. Everything is working fine now :) (with systemd).
I'm currently upgrading everything to ~amd64, and will then see if openrc is working or not.

**Comment by zhtengw** [comment] 2019-05-04 13:05
Do not need to upgrade all to ~amd64. Just emerge elogind, rebuild dde-daemon and dde-session-ui with “elogind” USE flag enabled. It should work.

Best regards,
Aten

**Comment by zhtengw** [comment] 2019-05-04 13:18
@SleepyMario, please sync this overlay before you trying. I just fixed some building issue.

**Comment by SleepyMario** [comment] 2019-05-04 14:47
@zhtengw Okay, I've synced the overlay and changed to openrc. Everything is working fine, but there is 1 problem left. Portage is asking for a rebuild with 'emerge @preserved-rebuild' of x11-wm/deepin-wm, which then fails. 
This is the log for x11-wm/deepin-wm: http://dpaste.com/3M8KJ23
And this is the log for x11-wm/deepin-mutter: http://dpaste.com/2E3BQBC (it looks like there's something wrong with it, but I'm not sure.)

mutter itself is not important to me, as I prefer using kwin. The mutter USE flag is disabled in both virtual/dde-wm and dde-base/dde-meta.

**Comment by zhtengw** [comment] 2019-05-04 16:28
@SleepyMario I see. When deepin-mutter build with "wayland" USE flag enabled, it need libsystemd. I omited it before and fixed it now.

**Comment by SleepyMario** [comment] 2019-05-04 17:34
@zhtengw Cool, everything is working now. 
谢谢你的协助！

**Comment by zhtengw** [comment] 2019-05-04 18:54
@SleepyMario, thanks for your discussion. You help me a lot.

**Closed** 2020-01-08 16:28 UTC
Labels: enhancement, help wanted
